#!/bin/bash -v

if [ $# -gt 0 ]; then
    repeat $1 do { java -jar target/ishihara-0.1.0-SNAPSHOT-standalone.jar -x 1200 -y 600 -r pdf } done
else
    java -jar target/ishihara-0.1.0-SNAPSHOT-standalone.jar -x 1200 -y 600 -r pdf
fi

